import streamlit as st
import nest_asyncio
from io import BytesIO
from agno.agent import Agent
from agno.document.reader.pdf_reader import PDFReader
from agno.models.ollama import Ollama
from agno.knowledge.pdf import PDFKnowledgeBase
from agno.tools.duckduckgo import DuckDuckGoTools
from agno.embedder.ollama import OllamaEmbedder
from agno.vectordb.chroma import ChromaDb
from agno.storage.agent.sqlite import SqliteAgentStorage

# Apply nest_asyncio to allow nested event loops, required for running async functions in Streamlit
nest_asyncio.apply()

# --- Fully local setup ------------------------------------------------------
# No OpenAI key, no Docker, no Postgres, nothing leaves your machine.
#   - Chat + embeddings -> Ollama, running locally on port 11434
#   - Chat/session history -> SQLite file
#   - Vector embeddings    -> local ChromaDB folder
# All three directories/files below are created automatically on first run.
DB_FILE = "tmp/agent_storage.db"
CHROMA_PATH = "tmp/chromadb"
PDF_DIR = "tmp/pdfs"  # placeholder dir; PDFKnowledgeBase requires a path, but this app
                      # loads uploaded PDFs directly via load_documents(), not from disk

# Ollama's embedding models report their own vector size; nomic-embed-text uses 768.
# If you switch embedding models, update this to match.
EMBEDDING_DIMENSIONS = 768


# Function to set up the Assistant, utilizing caching for resource efficiency
@st.cache_resource
def setup_assistant(chat_model_id: str, embed_model_id: str, ollama_host: str) -> Agent:
    """Initializes and returns an AI Assistant agent with caching for efficiency.

    This function sets up an AI Assistant agent using a local Ollama chat model
    and configures it with a knowledge base, storage, and web search tools. The
    assistant is designed to first search its knowledge base before querying the
    internet, providing clear and concise answers.

    Args:
        chat_model_id (str): The Ollama model to use for chat (e.g. "llama3.1", "mistral").
        embed_model_id (str): The Ollama model to use for embeddings (e.g. "nomic-embed-text").
        ollama_host (str): URL where the local Ollama server is running.

    Returns:
        Agent: An initialized Assistant agent configured with a language model,
        knowledge base, storage, and additional tools for enhanced functionality."""
    llm = Ollama(id=chat_model_id, host=ollama_host)
    # Set up the Assistant with storage, knowledge base, and tools
    return Agent(
        agent_id="auto_rag_agent",  # Name of the Assistant
        model=llm,  # Language model to be used
        storage=SqliteAgentStorage(table_name="auto_rag_storage", db_file=DB_FILE),
        knowledge=PDFKnowledgeBase(
            path=PDF_DIR,
            vector_db=ChromaDb(
                collection="auto_rag_docs_ollama",
                embedder=OllamaEmbedder(id=embed_model_id, dimensions=EMBEDDING_DIMENSIONS, host=ollama_host),
                path=CHROMA_PATH,
                persistent_client=True,
            ),
            num_documents=3,
        ),
        tools=[DuckDuckGoTools()],  # Additional tool for web search via DuckDuckGo
        instructions=[
            "Search your knowledge base first.",
            "If not found, search the internet.",
            "Provide clear and concise answers.",
        ],
        show_tool_calls=True,
        search_knowledge=True,
        markdown=True,
        debug_mode=True,
    )


# Function to add a PDF document to the knowledge base
def add_document(agent: Agent, file: BytesIO):
    """Add a PDF document to the agent's knowledge base.

    This function reads a PDF document from a file-like object and adds its contents to the specified agent's knowledge base. If the document is successfully read, the contents are loaded into the knowledge base with the option to upsert existing data.

    Args:
        agent (Agent): The agent whose knowledge base will be updated.
        file (BytesIO): A file-like object containing the PDF document to be added.

    Returns:
        None: The function does not return a value but provides feedback on whether the operation was successful."""
    reader = PDFReader()
    docs = reader.read(file)
    if docs:
        agent.knowledge.load_documents(docs, upsert=True)
        st.success("Document added to the knowledge base.")
    else:
        st.error("Failed to read the document.")


# Function to query the Assistant and return a response
def query_assistant(agent: Agent, question: str) -> str:
    """Queries the Assistant and returns a response.

    Args:
        agent (Agent): An instance of the Agent class used to process the query.
        question (str): The question to be asked to the Assistant.

    Returns:
        str: The response generated by the Assistant for the given question."""
    return agent.run(question)


# Main function to handle Streamlit app layout and interactions
def main():
    """Main function to handle the layout and interactions for the Streamlit app.

    This function sets up the Streamlit app configuration, handles user inputs such
    as the local Ollama model choice, PDF uploads, and user questions, and interacts
    with an autonomous retrieval-augmented generation (RAG) assistant running fully
    on-device.

    The app allows users to upload PDF documents to enhance the knowledge base and
    submit questions to receive generated responses.

    Side Effects:
        - Configures Streamlit page and title.
        - Lets users pick which local Ollama models to use.
        - Allows users to upload PDF documents.
        - Displays responses generated by querying an assistant.

    Raises:
        StreamlitWarning: If Ollama is not reachable at the given host."""
    st.set_page_config(page_title="AutoRAG", layout="wide")
    st.title("🤖 Auto-RAG: Autonomous RAG, fully local with Ollama")
    st.caption(
        "Runs entirely on your machine — Ollama for chat + embeddings, SQLite for "
        "history, ChromaDB for vectors. No API key, no Docker, nothing leaves your device."
    )

    st.sidebar.header("⚙️ Local model settings")
    ollama_host = st.sidebar.text_input("Ollama host", value="http://localhost:11434")
    chat_model_id = st.sidebar.selectbox("Chat model", ["llama3.1", "mistral"], index=0)
    embed_model_id = st.sidebar.selectbox("Embedding model", ["nomic-embed-text"], index=0)
    st.sidebar.caption(
        "Make sure `ollama serve` is running and you've pulled these models, e.g.\n\n"
        f"`ollama pull {chat_model_id}`\n\n`ollama pull {embed_model_id}`"
    )

    assistant = setup_assistant(chat_model_id, embed_model_id, ollama_host)

    uploaded_file = st.sidebar.file_uploader("📄 Upload PDF", type=["pdf"])

    if uploaded_file and st.sidebar.button("🛠️ Add to Knowledge Base"):
        add_document(assistant, BytesIO(uploaded_file.read()))

    question = st.text_input("💬 Ask Your Question:")

    # When the user submits a question, query the assistant for an answer
    if st.button("🔍 Get Answer"):
        # Ensure the question is not empty
        if question.strip():
            with st.spinner("🤔 Thinking..."):
                try:
                    # Query the assistant and display the response
                    answer = query_assistant(assistant, question)
                    st.write("📝 **Response:**", answer.content)
                except Exception as e:
                    st.error(
                        f"Couldn't reach Ollama at {ollama_host}. Is `ollama serve` "
                        f"running and are the models pulled? ({e})"
                    )
        else:
            # Show an error if the question input is empty
            st.error("Please enter a question.")


# Entry point of the application
if __name__ == "__main__":
    main()
